from pydantic import BaseModel, Field
from typing import List, Dict, Any, Optional
from datetime import datetime

class ProjectCreate(BaseModel):
    prompt: str = Field(..., description="The main prompt to be executed by the collaborative agents.")

class TaskBase(BaseModel):
    id: str = Field(..., description="Unique task identifier, e.g. 'task_1'")
    title: str = Field(..., description="Human-readable title of the task")
    type: str = Field(..., description="Agent worker type, e.g. 'research', 'code_execution', 'writer'")
    depend_on_ids: List[str] = Field(default_factory=list, description="IDs of tasks that must finish before this task can start")
    input_data: Dict[str, Any] = Field(default_factory=dict, description="Input parameters passed to the agent")

class TaskResponse(BaseModel):
    id: str
    project_id: str
    title: str
    type: str
    status: str
    depend_on_ids: List[str]
    input_data: Dict[str, Any]
    output_data: Dict[str, Any]
    logs: str
    thoughts: str
    created_at: datetime
    updated_at: datetime

    class Config:
        from_attributes = True

class ProjectResponse(BaseModel):
    id: str
    prompt: str
    status: str
    created_at: datetime
    updated_at: datetime
    tasks: List[TaskResponse]

    class Config:
        from_attributes = True

class TaskGraphDefinition(BaseModel):
    """
    Schema generated by the LLM when parsing a user prompt into a DAG.
    """
    tasks: List[TaskBase] = Field(..., description="List of tasks in the Directed Acyclic Graph (DAG)")
